### ISSUE TITLE
Improvement: Add limits to settings pages to save people from them self.

### ISSUE THREAD

**Issue by OmniZenn** [Synthesis-Collective/HalgarisConsistentRPGLoot#22]
This was the error message:
![image](https://user-images.githubusercontent.com/84869772/136004314-c5eb1437-aa9c-411d-a904-e1fd920b77fa.png)

[Here's the log:](https://ufile.io/no07jmk8)

Also, I tried running the patcher a few times with high numbers for variation on armors/weapons and the patcher always runs for a while(longest I've seen was around 25mins for 5000) then Synthesis crashes before the patcher can finish.

**Comment by EzioTheDeadPoet** [comment]
what are your settings

**Comment by EzioTheDeadPoet** [comment]
the new settings should make it clearer what everything does. 
please consult the [README.md](https://github.com/Synthesis-Collective/HalgarisConsistentRPGLoot/blob/master/README.md) for the settings and which to be careful about.
