### ISSUE TITLE
Limit to specific leveled list and sublists

### ISSUE THREAD

**Issue by gittysock** [Synthesis-Collective/HalgarisConsistentRPGLoot#25]
Hello, I apologize if this is not posted in the right section (GitHub is not something I am totally used to), but this really isn't an issue but more of a request.

Is there a way to limit the the variations of items to a specific leveled list and its sublists? Ideally, I would like to use enchantments from my entire load order and create random variations with a specific leveled list and sublists.

For example, say I had a leveled item called "HalgariRPGLoot", and within that leveled item were sublists containing hundreds of mod-added armors and weapons. If I only wanted variations within the hypothetical leveled list "HalgariRPGLoot" and leave the rest of the game's leveled lists unaffected, how could I go about doing this?

**Comment by EzioTheDeadPoet** [comment]
this would require a complete rewrite.

**Comment by gittysock** [comment]
Got it, thanks!

**Comment by EzioTheDeadPoet** [comment]
One way to do something similar would be to have a working OWL setup(or similar) then patch that with this patcher and then clean it out manually. At least I would guess you could do it in that way. No guarantees tho.
