### ISSUE TITLE
Suggestions: Allow users to blacklist enchantments, mods and armor/weapon records

### ISSUE THREAD

**Issue by saberthesword** [Synthesis-Collective/HalgarisConsistentRPGLoot#26]
1. Some mods have effects that are marked as enchantments even though they aren't part of the typical enchantment (e.g. cowbell jingles from this mod (NSFW): https://www.nexusmods.com/skyrimspecialedition/mods/598)

2+3. Since some users use patchers like No Enchantment Restriction, the patcher runs on records like Farm Clothes

**Comment by EzioTheDeadPoet** [comment]
Fixed/Implemented with the 3.0 release (and was actually already in the code ~2years ago in my development branch, but it wasn't finished yet and I got hit with da big "procrastination"-debuff)
