### ISSUE TITLE
Is plugin whitelist working?

### ISSUE THREAD

**Issue by Hinkiii** [Synthesis-Collective/HalgarisConsistentRPGLoot#34]
It seems to create entries in the leveled lists but the log doesn't have any mention of generating enchantments

**Comment by EzioTheDeadPoet** [comment]
then the whitelisted mod doesn't have any valid enchanted items in its leveled lists.

**Comment by Hinkiii** [comment]
To add to this, running it off of Skyrim.esm, it'll add requirements for other plugins that are loaded, though again doesn't seem to generate enchantments. It mentions a number in the log, and it creates forms that I can see in SSE Edit, but can't find it ingame.
