### ISSUE TITLE
Unable to find 'Only process constructible equipment' option

### ISSUE THREAD

**Issue by ghamza1995-2** [Synthesis-Collective/HalgarisConsistentRPGLoot#35]
Synthesis says I have 3.2.0 ready to use and yet I don't see that option

![image](https://github.com/user-attachments/assets/7a583812-ee6a-4057-90fc-1b30336bce25)
![image](https://github.com/user-attachments/assets/639e11dd-d477-4f39-be56-68aed9eafa03)

**Comment by EzioTheDeadPoet** [comment]
The option was removed because it was causing issues regarding the collection of the enchantments.
Or it was something else.
But it definitely wasn't working as intended so I removed it. 
Guess I forgot to remove it from the readme.
